# Automatically generated by configure - do not modify
# Configured with: './configure'
prefix=/usr
includedir=/usr/include
libdir=/usr/lib
libdevdir=/usr/lib
relativelibdir=
mandir=/usr/man
datadir=/usr/share
CONFIG_HAVE_KERNEL_RWF_T=y
CC=gcc
